[build]
  base = "frontend"
  command = "bash ./netlify-build.sh"
  publish = "dist"

[build.environment]
  VITE_API_BASE = "https://anon-messenger-backend-production-7c1a.up.railway.app"
  VITE_WS_BASE = "wss://anon-messenger-backend-production-7c1a.up.railway.app"
  NODE_VERSION = "20.11.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200